# Generated by Django 4.2.5 on 2023-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='book_management.genre'),
        ),
    ]
