# Generated by Django 4.2.5 on 2023-09-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
