# Generated by Django 4.2.5 on 2023-09-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
