# Generated by Django 4.2.5 on 2023-09-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0007_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
