# Generated by Django 4.2.5 on 2023-09-27 10:45

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_poster',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='book_posters/'),
        ),
    ]
